### PR TITLE
SONARAZDO-393 Bump embedded .NET scanner to 7.1

### PR DESCRIPTION
**Pull request by 7PH**
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-393)

This release is a new major release, but the mentioned breaking change shouldn’t be one for us (change of default sonar.host.url) because we are always specifying it.

### CODE REVIEW

**Review by lucas-paulger-sonarsource — APPROVED** [review]

**Comment by martin-strecker-sonarsource** [comment]
FYI: The zip files of the [release 7.1.0.95705 ](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/7.1.0.95705) have the path inside the zip file encoded wrong. The path separator is a `\` instead of a `/`. This is fine for most tools, but some fail while others produce a warning. See our issue https://github.com/SonarSource/sonar-scanner-msbuild/issues/2086 for details.
You seem to use `toolLib.extractZip` here https://github.com/SonarSource/sonar-scanner-azdo/blob/master/src/common/latest/sonarqube/Scanner.ts#L40

Before you release, you should test if you have any problems with the extraction (warnings, errors, wrong file locations, etc.).

We already have a fix in place, and if you face any problems, we will release a patch for version 7.1. Just ping me in this thread or on Slack.

**Comment by 7PH** [comment]
Hello @martin-strecker-sonarsource , thanks for the heads up!

From the validation round I've made, it looks like it's working (both when we use `extractZip` from the azure lib, and when we use the embedded version

```text
2024-07-24T09:51:27.5932337Z ##[debug]Unzipped file to D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910
2024-07-24T09:51:27.5934625Z ##[debug]Absolute path for pathSegments: D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910,SonarScanner.MSBuild.exe = D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910\SonarScanner.MSBuild.exe
2024-07-24T09:51:27.5935436Z ##[debug]set SONAR_SCANNER_LOCATION=D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910\SonarScanner.MSBuild.exe
2024-07-24T09:51:27.5947083Z ##[debug]exec tool: D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910\SonarScanner.MSBuild.exe
2024-07-24T09:51:27.5947625Z ##[debug]arguments:
2024-07-24T09:51:27.5948119Z ##[debug]   begin
2024-07-24T09:51:27.5948606Z ##[debug]   /k:7ph_asdasdasdas
2024-07-24T09:51:27.5949080Z ##[debug]   /o:7ph
2024-07-24T09:51:27.5949554Z ##[debug]   /d:sonar.verbose=true
2024-07-24T09:51:27.5950524Z [command]D:\a\_temp\1059cbbb-d522-4be0-8ee0-fe8dc021a910\SonarScanner.MSBuild.exe begin /k:7ph_asdasdasdas /o:7ph /d:sonar.verbose=true
2024-07-24T09:51:27.6729788Z SonarScanner for MSBuild 7.1
2024-07-24T09:51:27.6730509Z Using the .NET Framework version of the Scanner for MSBuild
```

**Comment by andrei-epure-sonarsource** [comment]
@7PH The problem only occurs on Unix systems. On Windows it's fine (the logs you give are from Windows, using the `exe`).

Can the AZDO extension run also on Unix boxes, or is it by default running only on Windows machines?

**Comment by 7PH** [comment]
> Can the AZDO extension run also on Unix boxes, or is it by default running only on Windows machines?

No, the AzDO extension could very well be running on UNIX systems. I specified explicitly UNIX runners and indeed it failed
```text
/usr/bin/unzip /home/vsts/work/_temp/e07f9098-ec47-462b-a0dd-38a0fe4d52a2
Archive:  /home/vsts/work/_temp/e07f9098-ec47-462b-a0dd-38a0fe4d52a2
warning:  /home/vsts/work/_temp/e07f9098-ec47-462b-a0dd-38a0fe4d52a2 appears to use backslashes as path separators
```

This means we need a fix before updating the extension

**Comment by martin-strecker-sonarsource** [comment]
extractZip uses `tl.tool('unzip')` on unix:
https://github.com/microsoft/azure-pipelines-tool-lib/blob/830ec78dd0f0fe3d8aad5a82c469fe52f736b738/tool.ts#L569-L590
`tool` is defined here:
https://github.com/microsoft/azure-pipelines-task-lib/blob/7c0de0dba61afb899068c35d88257017bd3b4736/node/task.ts#L1592
it resolves "unzip" here:
https://github.com/microsoft/azure-pipelines-task-lib/blob/7c0de0dba61afb899068c35d88257017bd3b4736/node/toolrunner.ts#L71
which is definded here:
https://github.com/microsoft/azure-pipelines-task-lib/blob/7c0de0dba61afb899068c35d88257017bd3b4736/node/internal.ts#L398
It will find the `unzip` tool and `unzip` produces a warning and exists with error code 1 as described here:
https://github.com/SonarSource/sonar-scanner-msbuild/issues/2086

So we will likely see some kind of problem here:
* There will be a warning (hat might not be populated)
*  extraction may fails because of the exit code

**Comment by martin-strecker-sonarsource** [comment]
> Do you know when we can expect a fix?

We will start on the patch release at 1:30 pm and expect it to be ready until the end of the day.

**Comment by martin-strecker-sonarsource** [comment]
The release is done:
https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/7.1.1.96069

**Comment by 7PH** [comment]
I bumped the version and I confirmed that I was able to reproduce the error with UNIX runners on `7.1.0` but not with `7.1.1`.

@lucas-paulger-sonarsource , I've bumped the extension version as well, 

Thanks for the notifying us @martin-strecker-sonarsource @andrei-epure-sonarsource

**Pull request merged**
