### PR TITLE
BUILD-4839 Update the release workflow to the latest version

### PR DESCRIPTION
**Pull request by matemoln**
Updating the release workflow to use the v5 branch for future updates

### CODE REVIEW

**Comment by 7PH** [comment]
Hello @matemoln , I'm worried this won't work until tag prefixes are supported (see [BUILD-4722](https://sonarsource.atlassian.net/browse/BUILD-4722))

**Review by 7PH — COMMENTED** [review]
Hello @matemoln , I'm worried this won't work until tag prefixes are supported (see [BUILD-4722](https://sonarsource.atlassian.net/browse/BUILD-4722))

[BUILD-4722]: https://sonarsource.atlassian.net/browse/BUILD-4722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by matemoln** [comment]
@7PH thanks for the info, you are right! I'm closing this PR until BUILD-4722 is resolved

**Comment by matemoln** [comment]
[Release Action version 5.9.0](https://github.com/SonarSource/gh-action_release/releases/tag/5.9.0) has been published which allows the release tag to contain a project prefix

**Pull request merged**
